### ISSUE TITLE
Testless template fails to run

### ISSUE THREAD

**Issue by nekosaur** [vuetifyjs/webpack-advanced#10]
### Steps to reproduce
vue init vuetifyjs/webpack-advanced testproject
(Answer NO for creating tests)
cd testproject
npm install
npm run dev

### Versions
This is on Windows 10

### What is expected ?
The template should run, as per instructions.

### What is actually happening ?
dev-server.js errors out with:
```
fs.js:994
  binding.lstat(pathModule._makeLong(path), statValues);
          ^

Error: ENOENT: no such file or directory, lstat '<project path>\test'
```
### Workaround
Manually creating empty /test directory seems to work.

**Comment by maurop123** [comment]
This appear to be working after today's rebase. Closing this issue.
