### ISSUE TITLE
ignore .babelrc from npm publish

### ISSUE THREAD

**Issue by pwang2** [vuetifyjs/webpack-advanced#16]
In current documentation, at a-la-cater mode, we will need to install all the package like 'babel-preset-es2015' in the root project.  This is due to vuetify has .bebelrc shipped in npm package and  babelrc's [lookup behavior](https://babeljs.io/docs/usage/babelrc/#lookup-behavior).  

Another gotcha is, we need to keep in mind about the env(test, development, production) in vuetify/.babelrc. This is confusing and error prone.  It took me quite a while to handle different NODE_ENV here to adapt to my project. 

Exclude .babelrc from npm publish and leave the work to setup .babelrc to root project seems make more sense. Ideas? 

In the long term, definitively tree shaking will make way more sense.  Looking forward to see a `dist/vuetify.esm.js` file.

**Comment by nekosaur** [comment]
This issue should have been created in the vuetify repo

**Comment by pwang2** [comment]
Agree! Thanks. I will update there. 

Sent from my iPhone

On Sep 18, 2017, at 1:14 AM, Albert Kaaman <notifications@github.com> wrote:

This issue should have been created in the vuetify repo
