### ISSUE TITLE
vuetifyjs webpack advanced:  can't get /

### ISSUE THREAD

**Issue by freddymounirk** [vuetifyjs/webpack-advanced#21]
Installing webpack advanced , with linting (airbnb) , Tests , e2e tests . npm install , then npm run dev , it gives me " Can't get / "

Thanks

**Comment by saiberz** [comment]
Related to #18 
#20 fix this

**Comment by maurop123** [comment]
Works here too. @freddymounirk can you confirm if this fix worked for you?

**Comment by maurop123** [comment]
Closing this out

**Comment by freddymounirk** [comment]
@maurop123  thanks a lot :)
