### ISSUE TITLE
Theme variables are not working

### ISSUE THREAD

**Issue by Kinosnai** [vuetifyjs/webpack-advanced#28]
When I change colors on theme.styl file they are not reflected on the project. 

Just in case someone gets into the same problem I solved it changing line 4 on the main.styl file. Originally it shows this 
`@import '../../node_modules/vuetify/src/stylus/app'` 

Changed it for this 
`@import '../../node_modules/vuetify/src/stylus/main'`

I dont know if this was an error on the code or if there is a better workaround to solve this but in my case got it working perfectly.

**Comment by nekosaur** [comment]
This depends on if you've enabled custom theming during setup.
